name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Sets up AWS profile.
      - name: Setup AWS environment
        env:
          BOT_CI_ACCESS_KEY_ID: ${{ secrets.BOT_CI_ACCESS_KEY_ID }}
          BOT_CI_SECRET_ACCESS_KEY: ${{ secrets.BOT_CI_SECRET_ACCESS_KEY }}
        run: |
          ./scripts/setup-aws-environment.sh
      - name: Install packages
        run: |
          npm ci
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Run linter
        run: |
          npm run lint
      - name: Run test
        env:
          AWS_PROFILE: ${{ vars.AWS_PROFILE }}
          AWS_SDK_LOAD_CONFIG: ${{ vars.AWS_SDK_LOAD_CONFIG }}
          ENV: ${{ vars.ENV }}
          REGION: ${{ vars.REGION }}
        run: |
          npm run test
